local count = 0
local failures = 0
local function expect(actual, expected, label)
    assert(actual == expected, (label or "value") .. ": expected " .. tostring(expected) .. ", got " .. tostring(actual))
end
local function test(name, callback)
    count += 1
    local ok, message = pcall(callback)
    if ok then
        print("PASS " .. name)
    else
        failures += 1
        print("FAIL " .. name .. ": " .. tostring(message))
    end
end
local function prompt(action, markerName)
    local names = { ["Retirar pacote"] = "PackagePickup", ["Entregar pacote"] = "PackageDropoff", ["Iniciar turno"] = "FastFood", ["Comprar lanche"] = "SnackShop" }
    createMissionMarker(city, markerName or names[action] or action, vector(0, 0, 0), action, "Test job")
    return lastPrompt
end
local function trigger(target, player)
    clock += 3
    target.fire(player)
end
local function unchanged(player, before)
    for name, value in pairs(before) do
        if name ~= "StatusText" then expect(player:GetAttribute(name), value, name) end
    end
end
local function snapshot(player) return table.clone(player.attributes) end

test("deposits conserve cash plus bank, cap transfers, and reject empty wallet", function()
    local p = newPlayer({ Cash = 325, BankBalance = 70 })
    local deposit = prompt("Depositar")
    trigger(deposit, p)
    expect(p:GetAttribute("Cash"), 75)
    expect(p:GetAttribute("BankBalance"), 320)
    trigger(deposit, p)
    expect(p:GetAttribute("Cash"), 0)
    expect(p:GetAttribute("BankBalance"), 395)
    local before = snapshot(p)
    trigger(deposit, p)
    unchanged(p, before)
end)

test("withdrawals conserve cash plus bank, cap transfers, and reject empty bank", function()
    local p = newPlayer({ Cash = 70, BankBalance = 325 })
    local withdraw = prompt("Sacar")
    trigger(withdraw, p)
    expect(p:GetAttribute("Cash"), 320)
    expect(p:GetAttribute("BankBalance"), 75)
    trigger(withdraw, p)
    expect(p:GetAttribute("Cash"), 395)
    expect(p:GetAttribute("BankBalance"), 0)
    local before = snapshot(p)
    trigger(withdraw, p)
    unchanged(p, before)
end)

test("apartment purchase applies price once and subsequent interaction enters home", function()
    local p = newPlayer({ Cash = 2000, Reputation = 3 })
    local buy = prompt("Comprar")
    trigger(buy, p)
    expect(p:GetAttribute("Cash"), 1150)
    expect(p:GetAttribute("OwnedProperties"), 1)
    expect(p:GetAttribute("PassiveIncome"), 75)
    expect(p:GetAttribute("NextIncomeAt"), clock + 60)
    expect(p:GetAttribute("Reputation"), 13)
    expect(Housing.entered[p], nil)
    local before = snapshot(p)
    trigger(buy, p)
    unchanged(p, before)
    expect(Housing.entered[p], 1)
end)

test("unaffordable apartment cannot be purchased", function()
    local p = newPlayer({ Cash = 849 })
    local before = snapshot(p)
    trigger(prompt("Comprar"), p)
    unchanged(p, before)
end)

test("mission rejects pickup and delivery before acceptance", function()
    local p = newPlayer()
    local before = snapshot(p)
    trigger(prompt("Retirar pacote"), p)
    unchanged(p, before)
    trigger(prompt("Entregar pacote"), p)
    unchanged(p, before)
end)

test("mission follows acceptance, pickup, delivery and pays once", function()
    local p = newPlayer({ Cash = 100, Energy = 50 })
    local accept = prompt("Missão principal")
    local pickup = prompt("Retirar pacote")
    local deliver = prompt("Entregar pacote")
    trigger(accept, p)
    expect(p:GetAttribute("MissionStage"), "Pickup")
    expect(p:GetAttribute("MissionReward"), 650)
    expect(p:GetAttribute("MissionExpiresAt"), clock + 180)
    expect(p:GetAttribute("Cash"), 100)
    local accepted = snapshot(p)
    trigger(accept, p)
    unchanged(p, accepted)
    trigger(deliver, p)
    unchanged(p, accepted)
    trigger(pickup, p)
    expect(p:GetAttribute("MissionStage"), "Deliver")
    expect(p:GetAttribute("Energy"), 40)
    local pickedUp = snapshot(p)
    trigger(pickup, p)
    unchanged(p, pickedUp)
    trigger(accept, p)
    unchanged(p, pickedUp)
    trigger(deliver, p)
    expect(p:GetAttribute("MissionStage"), "None")
    expect(p:GetAttribute("MissionReward"), 0)
    expect(p:GetAttribute("CurrentMission"), "Nenhuma")
    expect(p:GetAttribute("MissionExpiresAt"), 0)
    expect(p:GetAttribute("MissionCompletions"), 1)
    expect(p:GetAttribute("Cash"), 750)
    expect(p:GetAttribute("Reputation"), 15)
    local completed = snapshot(p)
    trigger(deliver, p)
    unchanged(p, completed)
    trigger(accept, p)
    expect(p:GetAttribute("MissionStage"), "Pickup")
    expect(p:GetAttribute("Cash"), 750)
end)

test("mission pickup with insufficient energy does not consume the package", function()
    local p = newPlayer({ Energy = 9, MissionStage = "Pickup", MissionReward = 650 })
    local before = snapshot(p)
    trigger(prompt("Retirar pacote"), p)
    unchanged(p, before)
end)

test("job with insufficient energy changes no gameplay attributes", function()
    local p = newPlayer({ Energy = 4 })
    local before = snapshot(p)
    trigger(prompt("Iniciar turno"), p)
    unchanged(p, before)
end)

test("job prompt starts timed shift and only tick at deadline pays", function()
    local p = newPlayer({ Cash = 0, Energy = 32, Reputation = 29, Wanted = 4 })
    trigger(prompt("Iniciar turno", "StreetDeal"), p)
    expect(p:GetAttribute("Cash"), 0)
    expect(p:GetAttribute("WorkActive"), true)
    expect(p:GetAttribute("Energy"), 0)
    clock = p:GetAttribute("WorkEndsAt")
    JobService.tick(clock)
    expect(p:GetAttribute("Cash"), 422)
    expect(p:GetAttribute("Reputation"), 37)
    expect(p:GetAttribute("Wanted"), 5)
    expect(p:GetAttribute("WorkCompletions"), 1)
    expect(p:GetAttribute("WorkActive"), false)
end)

test("distance guard rejects out-of-range actions and allows the boundary", function()
    local p = newPlayer()
    local work = prompt("Depositar")
    p.Character.root.Position = vector(14.01, 0, 0)
    local before = snapshot(p)
    trigger(work, p)
    unchanged(p, before)
    p.Character.root.Position = vector(14, 0, 0)
    work.fire(p)
    expect(p:GetAttribute("Cash"), 750)
end)

test("cooldown blocks repeated and different prompts until two seconds pass", function()
    local p = newPlayer()
    local deposit = prompt("Depositar")
    local withdraw = prompt("Sacar")
    trigger(deposit, p)
    local before = snapshot(p)
    deposit.fire(p)
    unchanged(p, before)
    clock += 1.5
    withdraw.fire(p)
    unchanged(p, before)
    clock += 0.5
    withdraw.fire(p)
    expect(p:GetAttribute("Cash"), 1000)
    expect(p:GetAttribute("BankBalance"), 500)
end)

test("cooldown is independent for each player", function()
    local first, second = newPlayer(), newPlayer()
    local deposit = prompt("Depositar")
    trigger(deposit, first)
    deposit.fire(second)
    expect(first:GetAttribute("Cash"), 750)
    expect(second:GetAttribute("Cash"), 750)
end)

test("missing character, root, humanoid and dead humanoid reject interactions", function()
    local work = prompt("Iniciar turno")
    for _, missing in ipairs({ "character", "root", "humanoid", "health" }) do
        local p = newPlayer()
        if missing == "character" then p.Character = nil
        elseif missing == "root" then p.Character.root = nil
        elseif missing == "humanoid" then p.Character.humanoid = nil
        else p.Character.humanoid.Health = 0 end
        local before = snapshot(p)
        trigger(work, p)
        unchanged(p, before)
    end
end)

test("hospital restores energy without exceeding its maximum", function()
    local p = newPlayer({ Energy = 80 })
    trigger(prompt("Descansar"), p)
    expect(p:GetAttribute("Energy"), 100)
    expect(p:GetAttribute("Cash"), 1000)
end)

test("unknown activity never changes economy", function()
    local p = newPlayer()
    local before = snapshot(p)
    trigger(prompt("Unknown action"), p)
    unchanged(p, before)
end)

local function expectResetMission(player)
    expect(player:GetAttribute("MissionStage"), "None")
    expect(player:GetAttribute("MissionReward"), 0)
    expect(player:GetAttribute("MissionExpiresAt"), 0)
    expect(player:GetAttribute("CurrentMission"), "Nenhuma")
end

test("cancellation remote clears pickup and delivery without reward or energy refund", function()
    local accept = prompt("Missão principal")
    local pickup = prompt("Retirar pacote")
    local deliver = prompt("Entregar pacote")
    for _, stage in ipairs({ "Pickup", "Deliver" }) do
        local p = newPlayer({ Cash = 100, Reputation = 5, MissionCompletions = 3 })
        trigger(accept, p)
        if stage == "Deliver" then trigger(pickup, p) end
        local energy = p:GetAttribute("Energy")
        missionAction.fire(p, "Cancel")
        expectResetMission(p)
        expect(p:GetAttribute("Cash"), 100)
        expect(p:GetAttribute("Reputation"), 5)
        expect(p:GetAttribute("MissionCompletions"), 3)
        expect(p:GetAttribute("Energy"), energy)
        local cancelled = snapshot(p)
        missionAction.fire(p, "Cancel")
        trigger(deliver, p)
        unchanged(p, cancelled)
        trigger(accept, p)
        expect(p:GetAttribute("MissionStage"), "Pickup")
        expect(p:GetAttribute("MissionExpiresAt"), clock + 180)
    end
end)

test("cancellation remote ignores invalid actions and inactive missions", function()
    local p = newPlayer()
    local inactive = snapshot(p)
    missionAction.fire(p, "Cancel")
    unchanged(p, inactive)
    trigger(prompt("Missão principal"), p)
    local active = snapshot(p)
    for _, action in ipairs({ "cancel", "Deliver", "", 1, false, {} }) do
        missionAction.fire(p, action)
        unchanged(p, active)
    end
    missionAction.fire(p, nil)
    unchanged(p, active)
end)

test("mission expires at 180 seconds in either stage and never pays", function()
    local accept = prompt("Missão principal")
    local pickup = prompt("Retirar pacote")
    for _, stage in ipairs({ "Pickup", "Deliver" }) do
        local p = newPlayer({ Cash = 100, Reputation = 5, MissionCompletions = 3 })
        trigger(accept, p)
        local expiresAt = p:GetAttribute("MissionExpiresAt")
        if stage == "Deliver" then trigger(pickup, p) end
        expect(p:GetAttribute("MissionExpiresAt"), expiresAt, "pickup preserves deadline")
        clock = expiresAt - 1
        local active = snapshot(p)
        updatePlayerTimers(p, clock)
        unchanged(p, active)
        clock = expiresAt
        updatePlayerTimers(p, clock)
        expectResetMission(p)
        expect(p:GetAttribute("Cash"), 100)
        expect(p:GetAttribute("Reputation"), 5)
        expect(p:GetAttribute("MissionCompletions"), 3)
        local expired = snapshot(p)
        updatePlayerTimers(p, clock + 60)
        trigger(prompt("Entregar pacote"), p)
        unchanged(p, expired)
    end
end)

test("delivery at the deadline is rejected before the next timer tick", function()
    local p = newPlayer({ Cash = 100, Reputation = 5, MissionCompletions = 3 })
    trigger(prompt("Missão principal"), p)
    trigger(prompt("Retirar pacote"), p)
    clock = p:GetAttribute("MissionExpiresAt")
    prompt("Entregar pacote").fire(p)
    expectResetMission(p)
    expect(p:GetAttribute("Cash"), 100)
    expect(p:GetAttribute("Reputation"), 5)
    expect(p:GetAttribute("MissionCompletions"), 3)
end)

test("delivery just before the deadline succeeds once and survives the later timer tick", function()
    local p = newPlayer({ Cash = 100, Reputation = 5, MissionCompletions = 3 })
    trigger(prompt("Missão principal"), p)
    local expiresAt = p:GetAttribute("MissionExpiresAt")
    trigger(prompt("Retirar pacote"), p)
    clock = expiresAt - 0.01
    local deliver = prompt("Entregar pacote")
    deliver.fire(p)
    expectResetMission(p)
    expect(p:GetAttribute("Cash"), 750)
    expect(p:GetAttribute("Reputation"), 20)
    expect(p:GetAttribute("MissionCompletions"), 4)
    local completed = snapshot(p)
    clock = expiresAt
    updatePlayerTimers(p, clock)
    trigger(deliver, p)
    unchanged(p, completed)
end)

test("apartment income waits 60 seconds after purchase and pays each minute once", function()
    local p = newPlayer({ Cash = 2000 })
    trigger(prompt("Comprar"), p)
    local purchasedAt = clock
    clock = purchasedAt + 59
    updatePlayerTimers(p, clock)
    expect(p:GetAttribute("Cash"), 1150)
    expect(p:GetAttribute("NextIncomeAt"), purchasedAt + 60)
    clock = purchasedAt + 60
    updatePlayerTimers(p, clock)
    expect(p:GetAttribute("Cash"), 1225)
    expect(p:GetAttribute("NextIncomeAt"), purchasedAt + 120)
    updatePlayerTimers(p, clock)
    expect(p:GetAttribute("Cash"), 1225)
    clock = purchasedAt + 119
    updatePlayerTimers(p, clock)
    expect(p:GetAttribute("Cash"), 1225)
    clock = purchasedAt + 120
    updatePlayerTimers(p, clock)
    expect(p:GetAttribute("Cash"), 1300)
    expect(p:GetAttribute("NextIncomeAt"), purchasedAt + 180)
    updatePlayerTimers(p, clock)
    expect(p:GetAttribute("Cash"), 1300)
end)

test("delayed income ticks catch up without resetting cadence or paying twice", function()
    local p = newPlayer({ Cash = 2000 })
    trigger(prompt("Comprar"), p)
    local purchasedAt = clock
    clock = purchasedAt + 185
    updatePlayerTimers(p, clock)
    expect(p:GetAttribute("Cash"), 1375)
    expect(p:GetAttribute("NextIncomeAt"), purchasedAt + 240)
    updatePlayerTimers(p, clock)
    expect(p:GetAttribute("Cash"), 1375)
    clock = purchasedAt + 240
    updatePlayerTimers(p, clock)
    expect(p:GetAttribute("Cash"), 1450)
    expect(p:GetAttribute("NextIncomeAt"), purchasedAt + 300)
end)

test("income cadence belongs to each owner rather than a shared server minute", function()
    local first = newPlayer({ Cash = 2000 })
    local second = newPlayer({ Cash = 2000 })
    local buy = prompt("Comprar")
    trigger(buy, first)
    local firstPurchase = clock
    clock = firstPurchase + 30
    buy.fire(second)
    for _, elapsed in ipairs({ 60, 90, 120 }) do
        clock = firstPurchase + elapsed
        updatePlayerTimers(first, clock)
        updatePlayerTimers(second, clock)
        expect(first:GetAttribute("Cash"), elapsed == 120 and 1300 or 1225)
        expect(second:GetAttribute("Cash"), elapsed == 60 and 1150 or 1225)
    end
    expect(first:GetAttribute("NextIncomeAt"), firstPurchase + 180)
    expect(second:GetAttribute("NextIncomeAt"), firstPurchase + 150)
end)

test("inactive timers change nothing and expired missions do not block owned income", function()
    local inactive = newPlayer()
    local before = snapshot(inactive)
    updatePlayerTimers(inactive, clock + 600)
    unchanged(inactive, before)
    local p = newPlayer({ Cash = 2000 })
    trigger(prompt("Comprar"), p)
    trigger(prompt("Missão principal"), p)
    clock = p:GetAttribute("MissionExpiresAt")
    updatePlayerTimers(p, clock)
    expectResetMission(p)
    expect(p:GetAttribute("Cash"), 1375)
    expect(p:GetAttribute("MissionCompletions"), 0)
end)

test("three offers rotate only after successful completion and target the correct stop", function()
    local p = newPlayer({ Cash = 0 })
    local targets = { "PackageDropoff", "HospitalDropoff", "BankDropoff" }
    local rewards = { 650, 700, 800 }
    for index, targetName in ipairs(targets) do
        trigger(prompt("Missão principal"), p)
        expect(p:GetAttribute("MissionReward"), rewards[index])
        expect(p:GetAttribute("MissionTargetName"), "PackagePickup")
        trigger(prompt("Retirar pacote"), p)
        expect(p:GetAttribute("MissionTargetName"), targetName)
        local before = snapshot(p)
        trigger(prompt("Entregar pacote", "WrongDestination"), p)
        unchanged(p, before)
        trigger(prompt("Entregar pacote", targetName), p)
        expect(p:GetAttribute("MissionCompletions"), index)
        expect(p:GetAttribute("MissionTargetName"), "MainMission")
    end
    expect(p:GetAttribute("Cash"), 2150)
    expect(p:GetAttribute("OfferedMissionName"), "Entrega VIP")
end)

test("courier ranks add server rewards at five and fifteen completed deliveries", function()
    for _, completed in ipairs({ 4, 5, 14, 15 }) do
        local p = newPlayer({ MissionCompletions = completed })
        updateMissionOffer(p)
        local route = DeliveryRoutes.offer(completed)
        local bonus = completed >= 15 and 100 or completed >= 5 and 50 or 0
        expect(p:GetAttribute("OfferedMissionReward"), route.reward + bonus)
        trigger(prompt("Missão principal"), p)
        expect(p:GetAttribute("MissionReward"), route.reward + bonus)
        expect(p:GetAttribute("MissionExpiresAt"), clock + route.duration)
    end
end)

test("loading and unavailable data block rewards bank cancellation and passive income", function()
    local p = newPlayer({ DataReady = false, MissionStage = "Deliver", MissionReward = 650, PassiveIncome = 75, NextIncomeAt = clock })
    local before = snapshot(p)
    for _, action in ipairs({ "Depositar", "Sacar", "Comprar", "Iniciar turno", "Comprar lanche", "Entregar pacote", "Missão principal" }) do
        trigger(prompt(action), p)
    end
    missionAction.fire(p, "Cancel")
    updatePlayerTimers(p, clock + 600)
    unchanged(p, before)
end)

test("cancelling does not rotate offers or grant career progress", function()
    local p = newPlayer({ MissionCompletions = 1 })
    trigger(prompt("Missão principal"), p)
    local route, payment = p:GetAttribute("MissionRoute"), p:GetAttribute("MissionReward")
    missionAction.fire(p, "Cancel")
    trigger(prompt("Missão principal"), p)
    expect(p:GetAttribute("MissionRoute"), route)
    expect(p:GetAttribute("MissionReward"), payment)
    expect(p:GetAttribute("MissionCompletions"), 1)
end)

test("work excludes delivery and housing until cancelled through its remote", function()
    local p = newPlayer({ OwnedProperties = 1 })
    trigger(prompt("Iniciar turno"), p)
    local active = snapshot(p)
    trigger(prompt("Missão principal"), p)
    trigger(prompt("Comprar"), p)
    unchanged(p, active)
    expect(Housing.entered[p], nil)
    for _, action in ipairs({ "cancel", "Finish", 1, {} }) do
        jobAction.fire(p, action)
        unchanged(p, active)
    end
    jobAction.fire(p, "Cancel")
    expect(p:GetAttribute("WorkActive"), false)
    expect(p:GetAttribute("Cash"), 1000)
    expect(p:GetAttribute("Energy"), 85)
    trigger(prompt("Missão principal"), p)
    expect(p:GetAttribute("MissionStage"), "Pickup")
end)

test("delivery excludes work without reserving energy", function()
    local p = newPlayer()
    trigger(prompt("Missão principal"), p)
    local active = snapshot(p)
    trigger(prompt("Iniciar turno"), p)
    unchanged(p, active)
end)

test("shop prompt and inventory remote buy then consume with shared cooldown", function()
    local p = newPlayer({ Energy = 80 })
    trigger(prompt("Comprar lanche"), p)
    expect(p:GetAttribute("Cash"), 940)
    expect(p:GetAttribute("SnackCount"), 1)
    inventoryAction.fire(p, "UseSnack")
    expect(p:GetAttribute("SnackCount"), 1)
    clock += 2
    for _, action in ipairs({ "Buy", "usesnack", 1, {} }) do inventoryAction.fire(p, action) end
    expect(p:GetAttribute("SnackCount"), 1)
    inventoryAction.fire(p, "UseSnack")
    expect(p:GetAttribute("SnackCount"), 0)
    expect(p:GetAttribute("Energy"), 100)
    expect(p:GetAttribute("Cash"), 940)
end)

test("inventory and job remotes stay blocked during data loading", function()
    local p = newPlayer({ SnackCount = 2, Energy = 50 })
    trigger(prompt("Iniciar turno"), p)
    p:SetAttribute("DataReady", false)
    local before = snapshot(p)
    inventoryAction.fire(p, "UseSnack")
    jobAction.fire(p, "Cancel")
    unchanged(p, before)
    JobService.remove(p)
end)

test("first steps follow real jobs shopping delivery bank and home without duplicate bonuses", function()
    local p = newPlayer({ Cash = 1500, BankBalance = 0 })
    local cleanup = ObjectiveService.trackPlayer(p)
    local function claim(id, expectedClaims)
        expect(p:GetAttribute("ObjectiveId"), id)
        expect(p:GetAttribute("ObjectiveReady"), true)
        objectiveAction.fire(p, "Claim", id)
        expect(p:GetAttribute("ObjectiveClaims"), expectedClaims)
        local cash = p:GetAttribute("Cash")
        objectiveAction.fire(p, "Claim", id)
        expect(p:GetAttribute("Cash"), cash)
        expect(p:GetAttribute("ObjectiveClaims"), expectedClaims)
    end
    expect(p:GetAttribute("ObjectiveReady"), false)
    trigger(prompt("Iniciar turno"), p)
    clock = p:GetAttribute("WorkEndsAt")
    JobService.tick(clock)
    claim("first_shift", 1)
    trigger(prompt("Comprar lanche"), p)
    clock += 2
    inventoryAction.fire(p, "UseSnack")
    expect(p:GetAttribute("SnackCount"), 0)
    claim("packed_snack", 2)
    trigger(prompt("Missão principal"), p)
    trigger(prompt("Retirar pacote"), p)
    trigger(prompt("Entregar pacote"), p)
    claim("first_delivery", 3)
    trigger(prompt("Depositar"), p)
    expect(p:GetAttribute("ObjectiveProgress"), 250)
    trigger(prompt("Depositar"), p)
    claim("bank_reserve", 4)
    trigger(prompt("Comprar"), p)
    claim("first_home", 5)
    expect(p:GetAttribute("Cash"), 1570)
    expect(p:GetAttribute("BankBalance"), 500)
    expect(p:GetAttribute("ObjectiveId"), "steady_work")
    expect(p:GetAttribute("ObjectiveProgress"), 1)
    cleanup()
end)

test("objective remote rejects arbitrary actions IDs and incomplete progress", function()
    local p = newPlayer()
    local cleanup = ObjectiveService.trackPlayer(p)
    objectiveAction.fire(p, "Claim", "first_shift")
    expect(p:GetAttribute("Cash"), 1000)
    expect(p:GetAttribute("ObjectiveClaims"), 0)
    p:SetAttribute("WorkCompletions", 1)
    for _, action in ipairs({ "claim", "Complete", 1, false, {} }) do objectiveAction.fire(p, action, "first_shift") end
    for _, id in ipairs({ "city_courier", "", 1, false, {} }) do objectiveAction.fire(p, "Claim", id) end
    objectiveAction.fire(p, "Claim", nil)
    expect(p:GetAttribute("Cash"), 1000)
    expect(p:GetAttribute("ObjectiveClaims"), 0)
    p:SetAttribute("DataReady", false)
    expect(p:GetAttribute("ObjectiveReady"), false)
    objectiveAction.fire(p, "Claim", "first_shift")
    expect(p:GetAttribute("Cash"), 1000)
    p:SetAttribute("DataReady", true)
    objectiveAction.fire(p, "Claim", "first_shift")
    expect(p:GetAttribute("Cash"), 1100)
    cleanup()
end)

test("bank objective reflects real withdrawal before reward and does not spend the reserve", function()
    local p = newPlayer({ ObjectiveClaims = 3, BankBalance = 500 })
    local cleanup = ObjectiveService.trackPlayer(p)
    expect(p:GetAttribute("ObjectiveReady"), true)
    trigger(prompt("Sacar"), p)
    expect(p:GetAttribute("ObjectiveProgress"), 250)
    expect(p:GetAttribute("ObjectiveReady"), false)
    objectiveAction.fire(p, "Claim", "bank_reserve")
    expect(p:GetAttribute("Cash"), 1250)
    expect(p:GetAttribute("ObjectiveClaims"), 3)
    trigger(prompt("Depositar"), p)
    objectiveAction.fire(p, "Claim", "bank_reserve")
    expect(p:GetAttribute("Cash"), 1125)
    expect(p:GetAttribute("BankBalance"), 500)
    expect(p:GetAttribute("ObjectiveClaims"), 4)
    cleanup()
end)

print(string.format("%d/%d interaction checks passed (Luau with Roblox mocks).", count - failures, count))
assert(failures == 0, tostring(failures) .. " interaction checks failed")
